---
- name: restart webapp
  systemd:
    name: "{{ application_name }}"
    daemon_reload: yes
    state: restarted
  become: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
