---
- name: Install dependencies
  apt:
    package:
      - build-essential
      - git
      - gunicorn
      - nginx
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
    update_cache: yes
    cache_valid_time: '3600' # 1 hour
    state: latest
  become: yes

- name: Retrieve application
  git:
    repo: "{{ application_repo }}"
    dest: "{{ application_dir }}"

- name: Install gunicorn
  pip: 
    name: 'gunicorn'
    virtualenv: "{{ application_venv }}"
    virtualenv_command: 'python -m venv'

- name: Install requirements
  pip: 
    requirements: "{{ application_dir }}/requirements.txt"
    virtualenv: "{{ application_venv }}"
    virtualenv_command: 'python -m venv'

- name: Set service file
  template:
    src: gunicorn.service.j2
    dest: "/etc/systemd/system/{{ application_name }}.service"
  become: yes
  notify:
    - restart webapp

- name: Set nginx file
  template:
    src: default.nginx.j2 
    dest: "/etc/nginx/sites-available/default"
  become: yes
  notify:
    - restart nginx
